id: ABC0AC800
title: The Root Verses on the Six Bardos
type: translation
source_metadata:
  languages:
  - en
  - de
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:12:27.988703
  last_modified_at: 2022-03-01 00:12:27.988707
